# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0003_auto_20170503_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
    ]
