# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0004_auto_20170503_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис'),
        ),
    ]
