# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170506_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comment_ptr',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
